### ISSUE TITLE
Usage instructions and output examples

### ISSUE THREAD

**Issue by fdzaebel** [matdue/ibkr-steuerrechner#1]
Hello,

thank you very much for your work. Could you please share an usage instruction and some examples of the output of your tool?

**Comment by matdue** [comment]
Hi, this tool is still in a very early stage and not finished yet.

**Comment by matdue** [comment]
Hi, the first version has been finished. Please have a look, there is also an online version. The tool is in German only, I hope this is not a blocker for you.
